In [161]:
#%pip install pandas
import pandas as pd

In [162]:

import glob
folder_path = 'Data/*.csv' 
csv_files = glob.glob(folder_path)

dataframes = [pd.read_csv(file) for file in csv_files]
combined_df = pd.concat(dataframes, ignore_index=True)
print("Combined DataFrame:")
print(combined_df.head())

Combined DataFrame:
   PropertyID       PropType      taxkey            Address CondoProject  \
0     98422.0  Manufacturing  10011000.0    9400 N 124TH ST          NaN
1     98453.0     Commercial  30023110.0  10545 W DONGES CT          NaN
2     98490.0    Residential  40061000.0  9409 N MICHAEL CT          NaN
3     98495.0    Residential  40066000.0  9469 N MICHAEL CT          NaN
4     98545.0    Residential  50026000.0    9313 N JOYCE AV          NaN

   District    nbhd                         Style                  Extwall  \
0       9.0  6300.0                 Pole Building             Metal Siding
1       9.0  6202.0  Warehouse Building - 1 Story           Concrete Block
2       9.0    40.0                         Ranch  Fiber Cement/Hardiplank
3       9.0    40.0                         Tudor  Fiber Cement/Hardiplank
4       9.0    40.0                         Ranch           Aluminum/Vinyl

   Stories  Year_Built  Rooms FinishedSqft  Units  Bdrms  Fbath  Hbath  \
0      1.0      2005.0    NaN      18000.0    1.0    NaN    NaN    NaN
1      1.0      1973.0    NaN      27940.0    5.0    NaN    NaN    NaN
2      1.0      2006.0    9.0       2778.0    1.0    4.0    2.0    NaN
3      2.0      2006.0    9.0       2936.0    1.0    4.0    2.0    1.0
4      1.0      1980.0    5.0       1007.0    1.0    3.0    1.0    NaN

    Lotsize  Sale_date Sale_price
0       0.0  3/11/2019   675000.0
1  100188.0  9/13/2019  1300000.0
2   13831.0  7/25/2019   350000.0
3   10607.0  9/27/2019   380000.0
4    9170.0  8/23/2019   135000.0

In [163]:
combined_df.shape

(31898, 20)

changing the Date time Formatinto appropriate format

In [164]:
def convert_date(date):
    try:
        
        pd.to_datetime(date, format='%m/%d/%Y')
        return date  
    except ValueError:
        return pd.to_datetime(date, format='%Y-%m-%d').strftime('%m/%d/%Y')


combined_df['Sale_date'] = combined_df['Sale_date'].apply(convert_date)

In [165]:
combined_df.head(5)

,PropertyID,PropType,taxkey,Address,CondoProject,District,nbhd,Style,Extwall,Stories,Year_Built,Rooms,FinishedSqft,Units,Bdrms,Fbath,Hbath,Lotsize,Sale_date,Sale_price
0,98422.0,Manufacturing,10011000.0,9400 N 124TH ST,NaN,9.0,6300.0,Pole Building,Metal Siding,1.0,2005.0,NaN,18000.0,1.0,NaN,NaN,NaN,0.0,3/11/2019,675000.0
1,98453.0,Commercial,30023110.0,10545 W DONGES CT,NaN,9.0,6202.0,Warehouse Building - 1 Story,Concrete Block,1.0,1973.0,NaN,27940.0,5.0,NaN,NaN,NaN,100188.0,9/13/2019,1300000.0
2,98490.0,Residential,40061000.0,9409 N MICHAEL CT,NaN,9.0,40.0,Ranch,Fiber Cement/Hardiplank,1.0,2006.0,9.0,2778.0,1.0,4.0,2.0,NaN,13831.0,7/25/2019,350000.0
3,98495.0,Residential,40066000.0,9469 N MICHAEL CT,NaN,9.0,40.0,Tudor,Fiber Cement/Hardiplank,2.0,2006.0,9.0,2936.0,1.0,4.0,2.0,1.0,10607.0,9/27/2019,380000.0
4,98545.0,Residential,50026000.0,9313 N JOYCE AV,NaN,9.0,40.0,Ranch,Aluminum/Vinyl,1.0,1980.0,5.0,1007.0,1.0,3.0,1.0,NaN,9170.0,8/23/2019,135000.0

Cleaning the sale_price column

In [166]:

def clean_price(price):
    try:
        
        if isinstance(price, str):
            return float(price.replace('$', '').replace(',', ''))
        
        return float(price)
    except ValueError:
       
        return price

combined_df['Sale_price'] = combined_df['Sale_price'].apply(clean_price)
combined_df['Lotsize'] = combined_df['Lotsize'].apply(clean_price)

In [167]:
combined_df.dtypes

PropertyID      float64
PropType         object
taxkey          float64
Address          object
CondoProject     object
District        float64
nbhd            float64
Style            object
Extwall          object
Stories         float64
Year_Built      float64
Rooms           float64
FinishedSqft     object
Units           float64
Bdrms           float64
Fbath           float64
Hbath           float64
Lotsize         float64
Sale_date        object
Sale_price      float64
dtype: object

Converting Finished Sqft to numeric

In [168]:
combined_df['FinishedSqft'] = pd.to_numeric(combined_df['FinishedSqft'], errors='coerce')

In [169]:
combined_df.dtypes

PropertyID      float64
PropType         object
taxkey          float64
Address          object
CondoProject     object
District        float64
nbhd            float64
Style            object
Extwall          object
Stories         float64
Year_Built      float64
Rooms           float64
FinishedSqft    float64
Units           float64
Bdrms           float64
Fbath           float64
Hbath           float64
Lotsize         float64
Sale_date        object
Sale_price      float64
dtype: object

In [170]:
combined_df

,PropertyID,PropType,taxkey,Address,CondoProject,District,nbhd,Style,Extwall,Stories,Year_Built,Rooms,FinishedSqft,Units,Bdrms,Fbath,Hbath,Lotsize,Sale_date,Sale_price
0,98422.0,Manufacturing,1.001100e+07,9400 N 124TH ST,NaN,9.0,6300.0,Pole Building,Metal Siding,1.0,2005.0,NaN,18000.0,1.0,NaN,NaN,NaN,0.0,3/11/2019,675000.0
1,98453.0,Commercial,3.002311e+07,10545 W DONGES CT,NaN,9.0,6202.0,Warehouse Building - 1 Story,Concrete Block,1.0,1973.0,NaN,27940.0,5.0,NaN,NaN,NaN,100188.0,9/13/2019,1300000.0
2,98490.0,Residential,4.006100e+07,9409 N MICHAEL CT,NaN,9.0,40.0,Ranch,Fiber Cement/Hardiplank,1.0,2006.0,9.0,2778.0,1.0,4.0,2.0,NaN,13831.0,7/25/2019,350000.0
3,98495.0,Residential,4.006600e+07,9469 N MICHAEL CT,NaN,9.0,40.0,Tudor,Fiber Cement/Hardiplank,2.0,2006.0,9.0,2936.0,1.0,4.0,2.0,1.0,10607.0,9/27/2019,380000.0
4,98545.0,Residential,5.002600e+07,9313 N JOYCE AV,NaN,9.0,40.0,Ranch,Aluminum/Vinyl,1.0,1980.0,5.0,1007.0,1.0,3.0,1.0,NaN,9170.0,8/23/2019,135000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31893,260621.0,Residential,7.160316e+09,6506 S 19TH ST,NaN,13.0,4920.0,Ranch,Aluminum/Vinyl,1.0,1960.0,5.0,891.0,1.0,3.0,2.0,0.0,6000.0,11/15/2023,277000.0
31894,260622.0,Residential,7.160317e+09,6500 S 19TH ST,NaN,13.0,4920.0,Ranch,Aluminum/Vinyl,1.0,1960.0,5.0,965.0,1.0,3.0,1.0,0.0,5891.0,08/04/2023,245000.0
31895,260630.0,Condominium,7.160327e+09,1928 W SALEM ST,COLLEGE HEIGHTS,13.0,5360.0,Low Rise 1-3 Stories,NaN,1.0,1974.0,5.0,1141.0,1.0,2.0,2.0,0.0,1.0,05/30/2023,168000.0
31896,260655.0,Condominium,7.160352e+09,6322 S 20TH ST,COLLEGE HEIGHTS,13.0,5360.0,Low Rise 1-3 Stories,NaN,2.0,1974.0,6.0,1048.0,1.0,2.0,1.0,0.0,1.0,10/10/2023,150000.0
31897,260668.0,Condominium,7.160365e+09,6376 S 20TH ST,COLLEGE HEIGHTS,13.0,5360.0,Low Rise 1-3 Stories,NaN,2.0,1974.0,10.0,1100.0,1.0,4.0,1.0,1.0,1.0,06/12/2023,140000.0

checking for duplicate rows, Dropping the duplicate rows

In [171]:
combined_df[combined_df.duplicated(keep=False)]

,PropertyID,PropType,taxkey,Address,CondoProject,District,nbhd,Style,Extwall,Stories,Year_Built,Rooms,FinishedSqft,Units,Bdrms,Fbath,Hbath,Lotsize,Sale_date,Sale_price
210,102594.0,Lg Apartment,7.401960e+08,8243-8255 N 107TH ST,NaN,9.0,6970.0,Subsidized Apartments,Brick on Frame,2.0,1979.0,0.0,61204.0,56.0,2.0,NaN,NaN,154159.0,12/10/2019,2000000.0
211,102594.0,Lg Apartment,7.401960e+08,8243-8255 N 107TH ST,NaN,9.0,6970.0,Subsidized Apartments,Brick on Frame,2.0,1979.0,0.0,61204.0,56.0,2.0,NaN,NaN,154159.0,12/10/2019,2000000.0
358,106116.0,Residential,1.180100e+09,7737 W BEECHWOOD AV,NaN,9.0,480.0,Ranch,Aluminum/Vinyl,1.0,1968.0,7.0,1418.0,1.0,3.0,1.0,1.0,7800.0,9/4/2019,90000.0
359,106116.0,Residential,1.180100e+09,7737 W BEECHWOOD AV,NaN,9.0,480.0,Ranch,Aluminum/Vinyl,1.0,1968.0,7.0,1418.0,1.0,3.0,1.0,1.0,7800.0,9/4/2019,90000.0
510,110205.0,Lg Apartment,1.450101e+09,9905-9909 W FOND DU LAC AV,NaN,2.0,6970.0,AP4 (Conv Apt with 21 or more Units),Brick,2.0,1972.0,0.0,27988.0,27.0,2.0,NaN,NaN,65974.0,5/24/2019,1100000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18916,856464.0,Condominium,7.160347e+09,6330 S 20TH ST,COLLEGE HEIGHTS,13.0,5360.0,Low Rise 1-3 Stories,NaN,1.0,1974.0,5.0,NaN,1.0,2.0,1.0,1.0,1.0,8/27/2020,110000.0
18917,857786.0,Condominium,7.160366e+09,6378 S 20TH ST,COLLEGE HEIGHTS,13.0,5360.0,Low Rise 1-3 Stories,NaN,2.0,1974.0,5.0,NaN,1.0,2.0,1.0,1.0,1.0,9/16/2020,95000.0
18918,857816.0,Condominium,7.160367e+09,6366 S 20TH ST,COLLEGE HEIGHTS,13.0,5360.0,Low Rise 1-3 Stories,NaN,2.0,1974.0,5.0,NaN,1.0,2.0,1.0,1.0,1.0,9/29/2020,100000.0
18919,859581.0,Condominium,7.160369e+09,6380 S 20TH ST,COLLEGE HEIGHTS,13.0,5360.0,Low Rise 1-3 Stories,NaN,2.0,1974.0,5.0,NaN,1.0,2.0,1.0,1.0,1.0,11/2/2020,114500.0
18920,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
combined_df=combined_df.drop_duplicates(keep='first')

In [173]:
#data[data.duplicated(keep=False)]
combined_df.shape

(25490, 20)

In [174]:
def null_values(x):
    print(x.isna().sum())

null_values(combined_df)

PropertyID          1
PropType            9
taxkey              1
Address             1
CondoProject    22211
District            2
nbhd               26
Style              59
Extwall          3418
Stories           128
Year_Built         47
Rooms            1308
FinishedSqft     5286
Units               1
Bdrms            1308
Fbath             608
Hbath            4791
Lotsize             1
Sale_date           1
Sale_price         11
dtype: int64

In [175]:
combined_df_district_3=combined_df[combined_df['District']==3]

In [176]:
null_values(combined_df_district_3)
combined_df_district_3.shape

PropertyID         0
PropType           0
taxkey             0
Address            0
CondoProject    1083
District           0
nbhd               0
Style              5
Extwall          716
Stories            6
Year_Built         4
Rooms             80
FinishedSqft     419
Units              0
Bdrms             80
Fbath             54
Hbath            348
Lotsize            0
Sale_date          0
Sale_price         0
dtype: int64

(1790, 20)

In [149]:
#we have null values for CondoProject up to 1083, so it's efficent to drop the column

In [239]:
combined_df_district_3.drop(['CondoProject','Extwall'],axis=1,inplace=True)
null_values(combined_df_district_3)

KeyError: "['CondoProject', 'Extwall'] not found in axis"

In [178]:
combined_df_district_3=combined_df_district_3.dropna(subset=['Rooms','nbhd','Address','Fbath','Bdrms'],axis=0)
null_values(combined_df_district_3)
combined_df_district_3.shape

PropertyID        0
PropType          0
taxkey            0
Address           0
District          0
nbhd              0
Style             0
Stories           2
Year_Built        0
Rooms             0
FinishedSqft    402
Units             0
Bdrms             0
Fbath             0
Hbath           294
Lotsize           0
Sale_date         0
Sale_price        0
dtype: int64

(1662, 18)

Getting sqft data from osm polygon using arcGis pro

In [179]:
combined_df_district_3['Location']=combined_df_district_3['Address']+ ',' + 'Milwaukee'+ ',' +'wisconsin'

In [180]:

combined_sqft_null = combined_df_district_3[combined_df_district_3['FinishedSqft'].isnull()]

In [181]:
combined_sqft_null

,PropertyID,PropType,taxkey,Address,District,nbhd,Style,Stories,Year_Built,Rooms,FinishedSqft,Units,Bdrms,Fbath,Hbath,Lotsize,Sale_date,Sale_price,Location
8207,855897.0,Residential,2.780012e+09,2910 E KENWOOD BL,3.0,3060.0,Colonial,2.0,1922.0,10.0,NaN,1.0,5.0,3.0,2.0,7200.0,7/24/2020,815000.0,"2910 E KENWOOD BL,Milwaukee,wisconsin"
8208,856023.0,Residential,2.780023e+09,2808 E KENWOOD BL,3.0,3060.0,Mansion,2.0,1908.0,12.0,NaN,1.0,7.0,3.0,3.0,12000.0,8/14/2020,750000.0,"2808 E KENWOOD BL,Milwaukee,wisconsin"
8209,863164.0,Residential,2.780035e+09,3102 N HACKETT AV,3.0,3060.0,Mansion,2.0,1922.0,11.0,NaN,1.0,5.0,3.0,2.0,8400.0,12/24/2020,690000.0,"3102 N HACKETT AV,Milwaukee,wisconsin"
8210,855891.0,Residential,2.780058e+09,3218 N DOWNER AV,3.0,3160.0,Duplex N/S,2.0,1958.0,12.0,NaN,2.0,7.0,3.0,1.0,5160.0,8/5/2020,377600.0,"3218 N DOWNER AV,Milwaukee,wisconsin"
8211,850562.0,Residential,2.780073e+09,3234 N HACKETT AV,3.0,3060.0,Residence O/S 2sty+,2.0,1906.0,10.0,NaN,1.0,6.0,3.0,0.0,6000.0,3/24/2020,449000.0,"3234 N HACKETT AV,Milwaukee,wisconsin"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9825,862388.0,Condominium,3.601691e+09,"1691 N MARSHALL ST, Unit 1",3.0,5904.0,Condo Townhouse,4.0,2006.0,5.0,NaN,1.0,3.0,2.0,1.0,0.0,6/30/2020,385000.0,"1691 N MARSHALL ST, Unit 1,Milwaukee,wisconsin"
9826,853139.0,Condominium,3.601703e+09,"1541 N JEFFERSON ST, Unit 201",3.0,5894.0,Mid RIse 4-12 Stories,1.0,2008.0,4.0,NaN,1.0,2.0,1.0,0.0,0.0,6/10/2020,234800.0,"1541 N JEFFERSON ST, Unit 201,Milwaukee,wisconsin"
9829,861454.0,Condominium,3.601732e+09,"1541 N JEFFERSON ST, Unit 410",3.0,5894.0,Mid RIse 4-12 Stories,1.0,2008.0,4.0,NaN,1.0,2.0,2.0,0.0,0.0,11/13/2020,316000.0,"1541 N JEFFERSON ST, Unit 410,Milwaukee,wisconsin"
9830,856213.0,Condominium,3.601740e+09,"1541 N JEFFERSON ST, Unit 510",3.0,5894.0,Mid RIse 4-12 Stories,1.0,2008.0,4.0,NaN,1.0,2.0,2.0,0.0,0.0,8/12/2020,314000.0,"1541 N JEFFERSON ST, Unit 510,Milwaukee,wisconsin"
9831,856405.0,Condominium,3.601792e+09,"1681-B N HUMBOLDT AV, Unit 2",3.0,5824.0,Low Rise 1-3 Stories,3.0,2008.0,8.0,NaN,1.0,2.0,2.0,2.0,0.0,8/13/2020,365000.0,"1681-B N HUMBOLDT AV, Unit 2,Milwaukee,wisconsin"

In [98]:
%pip install geopy

Requirement already satisfied: geopy in c:\users\naduk\anaconda3\lib\site-packages (2.4.1)
Requirement already satisfied: geographiclib<3,>=1.52 in c:\users\naduk\anaconda3\lib\site-packages (from geopy) (2.0)
Note: you may need to restart the kernel to use updated packages.

In [99]:
%pip install geopy
from geopy.geocoders import Nominatim
import time

lat = []
long = []
geolocator = Nominatim(user_agent='app',timeout=4)

Requirement already satisfied: geopy in c:\users\naduk\anaconda3\lib\site-packages (2.4.1)
Requirement already satisfied: geographiclib<3,>=1.52 in c:\users\naduk\anaconda3\lib\site-packages (from geopy) (2.0)
Note: you may need to restart the kernel to use updated packages.

In [100]:
for name in combined_sqft_null['Location'][0:402]:
    location = geolocator.geocode(name)
    if location:  
        lat.append(location.latitude)  
        long.append(location.longitude) 
    else:
        lat.append(None)  
        long.append(None) 
        
time.sleep(1)

In [101]:
combined_sqft_null['latitude']=lat

C:\Users\naduk\AppData\Local\Temp\ipykernel_7768\1986575925.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_sqft_null['latitude']=lat

In [102]:
combined_sqft_null['longitude']=long

C:\Users\naduk\AppData\Local\Temp\ipykernel_7768\900207005.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_sqft_null['longitude']=long

In [103]:
combined_sqft_null.isna().sum()

PropertyID        0
PropType          0
taxkey            0
Address           0
District          0
nbhd              0
Style             0
Stories           0
Year_Built        0
Rooms             0
FinishedSqft    402
Units             0
Bdrms             0
Fbath             0
Hbath             0
Lotsize           0
Sale_date         0
Sale_price        0
Location          0
latitude        131
longitude       131
dtype: int64

In [104]:
combined_sqft_null=combined_sqft_null.dropna(subset=['latitude'])

In [105]:
combined_sqft_null

,PropertyID,PropType,taxkey,Address,District,nbhd,Style,Stories,Year_Built,Rooms,FinishedSqft,Units,Bdrms,Fbath,Hbath,Lotsize,Sale_date,Sale_price,Location,latitude,longitude
8209,863164.0,Residential,2.780035e+09,3102 N HACKETT AV,3.0,3060.0,Mansion,2.0,1922.0,11.0,NaN,1.0,5.0,3.0,2.0,8400.0,12/24/2020,690000.0,"3102 N HACKETT AV,Milwaukee,wisconsin",43.074923,-87.876505
8210,855891.0,Residential,2.780058e+09,3218 N DOWNER AV,3.0,3160.0,Duplex N/S,2.0,1958.0,12.0,NaN,2.0,7.0,3.0,1.0,5160.0,8/5/2020,377600.0,"3218 N DOWNER AV,Milwaukee,wisconsin",43.076113,-87.877580
8211,850562.0,Residential,2.780073e+09,3234 N HACKETT AV,3.0,3060.0,Residence O/S 2sty+,2.0,1906.0,10.0,NaN,1.0,6.0,3.0,0.0,6000.0,3/24/2020,449000.0,"3234 N HACKETT AV,Milwaukee,wisconsin",43.076458,-87.876441
8212,852109.0,Residential,2.780076e+09,3235 N SHEPARD AV,3.0,3060.0,Residence O/S 2sty+,2.0,1908.0,9.0,NaN,1.0,5.0,1.0,1.0,4200.0,4/28/2020,303000.0,"3235 N SHEPARD AV,Milwaukee,wisconsin",43.076450,-87.874725
8213,852020.0,Residential,2.780099e+09,3218 N SHEPARD AV,3.0,3060.0,Residence O/S 2sty+,2.0,1904.0,9.0,NaN,1.0,4.0,3.0,1.0,4800.0,5/7/2020,494000.0,"3218 N SHEPARD AV,Milwaukee,wisconsin",43.076120,-87.874173
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9781,856126.0,Residential,3.600403e+09,1027-1029 E KEWAUNEE ST,3.0,3240.0,Duplex O/S,2.0,1900.0,12.0,NaN,2.0,5.0,2.0,0.0,3450.0,3/13/2020,243000.0,"1027-1029 E KEWAUNEE ST,Milwaukee,wisconsin",43.051751,-87.899527
9785,856135.0,Residential,3.600536e+09,1512-1514 N MARSHALL ST,3.0,3240.0,Duplex O/S,2.0,1890.0,11.0,NaN,2.0,4.0,2.0,0.0,3840.0,7/24/2020,280000.0,"1512-1514 N MARSHALL ST,Milwaukee,wisconsin",43.041708,-87.900573
9786,850242.0,Residential,3.600541e+09,1534 N MARSHALL ST,3.0,3240.0,Duplex O/S,2.0,1886.0,12.0,NaN,2.0,6.0,2.0,0.0,3840.0,3/27/2020,232500.0,"1534 N MARSHALL ST,Milwaukee,wisconsin",43.050163,-87.900609
9788,851581.0,Residential,3.600674e+09,1529-1531 N CASS ST,3.0,3240.0,Duplex O/S,2.0,1893.0,14.0,NaN,2.0,5.0,3.0,0.0,3840.0,4/23/2020,375000.0,"1529-1531 N CASS ST,Milwaukee,wisconsin",43.046942,-87.902241
9806,856513.0,Condominium,3.601272e+09,1682 N ASTOR ST,3.0,5955.0,Condo Duplex,2.0,1887.0,5.0,NaN,1.0,2.0,2.0,0.0,1.0,8/27/2020,210000.0,"1682 N ASTOR ST,Milwaukee,wisconsin",43.052498,-87.899305

In [107]:
combined_sqft_null.to_csv('Data1/null_sqft.csv', index=False)

Creating the finished Sqft data set

In [182]:
combined_sqft_not_null = combined_df_district_3[combined_df_district_3['FinishedSqft'].notnull()]

In [183]:
combined_sqft_not_null.shape

(1260, 19)

In [184]:
from geopy.geocoders import Nominatim
import time

lat = []
long = []
geolocator = Nominatim(user_agent='app',timeout=4)

In [186]:
for name in combined_sqft_not_null['Location'][999:1261]:
    location = geolocator.geocode(name)
    if location:  
        lat.append(location.latitude)  
        long.append(location.longitude) 
    else:
        lat.append(None)  
        long.append(None) 
        
time.sleep(1)

In [187]:
combined_sqft_not_null['latitude']=lat
combined_sqft_not_null['longitude']=long

C:\Users\naduk\AppData\Local\Temp\ipykernel_7768\2041355523.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_sqft_not_null['latitude']=lat
C:\Users\naduk\AppData\Local\Temp\ipykernel_7768\2041355523.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_sqft_not_null['longitude']=long

In [188]:
null_values(combined_sqft_not_null)

PropertyID        0
PropType          0
taxkey            0
Address           0
District          0
nbhd              0
Style             0
Stories           2
Year_Built        0
Rooms             0
FinishedSqft      0
Units             0
Bdrms             0
Fbath             0
Hbath           294
Lotsize           0
Sale_date         0
Sale_price        0
Location          0
latitude        587
longitude       587
dtype: int64

In [ ]:
null_sqft=pd.read_csv("sqft_Arcgis/sqft_ArcGIS.csv")

In [190]:
import pandas as pd
pd.set_option('display.max_columns', None)
null_sqft

,Join_Count,TARGET_FID,PropertyID,PropType,taxkey,Address,District,nbhd,Style,Stories,Year_Built,Rooms,FinishedSqft,Units,Bdrms,Fbath,Hbath,Lotsize,Sale_date,Sale_price,Location,latitude,longitude,AREA
0,1,1,863164.0,Residential,2.780035e+09,3102 N HACKETT AV,3.0,3060.0,Mansion,2.0,1922.0,11.0,NaN,1.0,5.0,3.0,2.0,8400.0,12/24/2020,690000.0,"3102 N HACKETT AV,Milwaukee,wisconsin",43.074923,-87.876505,310.808371
1,1,2,855891.0,Residential,2.780058e+09,3218 N DOWNER AV,3.0,3160.0,Duplex N/S,2.0,1958.0,12.0,NaN,2.0,7.0,3.0,1.0,5160.0,8/5/2020,377600.0,"3218 N DOWNER AV,Milwaukee,wisconsin",43.076113,-87.877580,147.531235
2,1,3,850562.0,Residential,2.780073e+09,3234 N HACKETT AV,3.0,3060.0,Residence O/S 2sty+,2.0,1906.0,10.0,NaN,1.0,6.0,3.0,0.0,6000.0,3/24/2020,449000.0,"3234 N HACKETT AV,Milwaukee,wisconsin",43.076458,-87.876441,134.644470
3,1,4,852109.0,Residential,2.780076e+09,3235 N SHEPARD AV,3.0,3060.0,Residence O/S 2sty+,2.0,1908.0,9.0,NaN,1.0,5.0,1.0,1.0,4200.0,4/28/2020,303000.0,"3235 N SHEPARD AV,Milwaukee,wisconsin",43.076450,-87.874725,120.952958
4,1,5,852020.0,Residential,2.780099e+09,3218 N SHEPARD AV,3.0,3060.0,Residence O/S 2sty+,2.0,1904.0,9.0,NaN,1.0,4.0,3.0,1.0,4800.0,5/7/2020,494000.0,"3218 N SHEPARD AV,Milwaukee,wisconsin",43.076120,-87.874173,109.889064
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
266,0,267,856126.0,Residential,3.600403e+09,1027-1029 E KEWAUNEE ST,3.0,3240.0,Duplex O/S,2.0,1900.0,12.0,NaN,2.0,5.0,2.0,0.0,3450.0,3/13/2020,243000.0,"1027-1029 E KEWAUNEE ST,Milwaukee,wisconsin",43.051751,-87.899527,NaN
267,0,268,856135.0,Residential,3.600536e+09,1512-1514 N MARSHALL ST,3.0,3240.0,Duplex O/S,2.0,1890.0,11.0,NaN,2.0,4.0,2.0,0.0,3840.0,7/24/2020,280000.0,"1512-1514 N MARSHALL ST,Milwaukee,wisconsin",43.041708,-87.900573,NaN
268,1,269,850242.0,Residential,3.600541e+09,1534 N MARSHALL ST,3.0,3240.0,Duplex O/S,2.0,1886.0,12.0,NaN,2.0,6.0,2.0,0.0,3840.0,3/27/2020,232500.0,"1534 N MARSHALL ST,Milwaukee,wisconsin",43.050163,-87.900608,154.536694
269,0,270,851581.0,Residential,3.600674e+09,1529-1531 N CASS ST,3.0,3240.0,Duplex O/S,2.0,1893.0,14.0,NaN,2.0,5.0,3.0,0.0,3840.0,4/23/2020,375000.0,"1529-1531 N CASS ST,Milwaukee,wisconsin",43.046942,-87.902241,NaN
270,1,271,856513.0,Condominium,3.601272e+09,1682 N ASTOR ST,3.0,5955.0,Condo Duplex,2.0,1887.0,5.0,NaN,1.0,2.0,2.0,0.0,1.0,8/27/2020,210000.0,"1682 N ASTOR ST,Milwaukee,wisconsin",43.052498,-87.899305,136.986958

In [191]:
null_sqft=null_sqft.drop(['Join_Count','TARGET_FID','taxkey','FinishedSqft'],axis=1)

In [192]:
null_sqft.shape

(271, 20)

In [193]:
null_sqft.columns

Index(['PropertyID', 'PropType', 'Address', 'District', 'nbhd', 'Style',
       'Stories', 'Year_Built', 'Rooms', 'Units', 'Bdrms', 'Fbath', 'Hbath',
       'Lotsize', 'Sale_date', 'Sale_price', 'Location', 'latitude',
       'longitude', 'AREA'],
      dtype='object')

In [194]:
combined_sqft_not_null.columns

Index(['PropertyID', 'PropType', 'taxkey', 'Address', 'District', 'nbhd',
       'Style', 'Stories', 'Year_Built', 'Rooms', 'FinishedSqft', 'Units',
       'Bdrms', 'Fbath', 'Hbath', 'Lotsize', 'Sale_date', 'Sale_price',
       'Location', 'latitude', 'longitude'],
      dtype='object')

In [195]:
combined_sqft_not_null=combined_sqft_not_null.drop(['taxkey'],axis=1)

In [56]:
null_sqft=null_sqft.drop(['latitude','longitude'],axis=1)
null_sqft

,PropertyID,PropType,Address,District,nbhd,Style,Stories,Year_Built,Rooms,Units,Bdrms,Fbath,Hbath,Lotsize,Sale_date,Sale_price,Location,AREA
0,863164.0,Residential,3102 N HACKETT AV,3.0,3060.0,Mansion,2.0,1922.0,11.0,1.0,5.0,3.0,2.0,8400.0,12/24/2020,690000.0,"3102 N HACKETT AV,Milwaukee,wisconsin",310.808371
1,855891.0,Residential,3218 N DOWNER AV,3.0,3160.0,Duplex N/S,2.0,1958.0,12.0,2.0,7.0,3.0,1.0,5160.0,8/5/2020,377600.0,"3218 N DOWNER AV,Milwaukee,wisconsin",147.531235
2,850562.0,Residential,3234 N HACKETT AV,3.0,3060.0,Residence O/S 2sty+,2.0,1906.0,10.0,1.0,6.0,3.0,0.0,6000.0,3/24/2020,449000.0,"3234 N HACKETT AV,Milwaukee,wisconsin",134.644470
3,852109.0,Residential,3235 N SHEPARD AV,3.0,3060.0,Residence O/S 2sty+,2.0,1908.0,9.0,1.0,5.0,1.0,1.0,4200.0,4/28/2020,303000.0,"3235 N SHEPARD AV,Milwaukee,wisconsin",120.952958
4,852020.0,Residential,3218 N SHEPARD AV,3.0,3060.0,Residence O/S 2sty+,2.0,1904.0,9.0,1.0,4.0,3.0,1.0,4800.0,5/7/2020,494000.0,"3218 N SHEPARD AV,Milwaukee,wisconsin",109.889064
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
266,856126.0,Residential,1027-1029 E KEWAUNEE ST,3.0,3240.0,Duplex O/S,2.0,1900.0,12.0,2.0,5.0,2.0,0.0,3450.0,3/13/2020,243000.0,"1027-1029 E KEWAUNEE ST,Milwaukee,wisconsin",NaN
267,856135.0,Residential,1512-1514 N MARSHALL ST,3.0,3240.0,Duplex O/S,2.0,1890.0,11.0,2.0,4.0,2.0,0.0,3840.0,7/24/2020,280000.0,"1512-1514 N MARSHALL ST,Milwaukee,wisconsin",NaN
268,850242.0,Residential,1534 N MARSHALL ST,3.0,3240.0,Duplex O/S,2.0,1886.0,12.0,2.0,6.0,2.0,0.0,3840.0,3/27/2020,232500.0,"1534 N MARSHALL ST,Milwaukee,wisconsin",154.536694
269,851581.0,Residential,1529-1531 N CASS ST,3.0,3240.0,Duplex O/S,2.0,1893.0,14.0,2.0,5.0,3.0,0.0,3840.0,4/23/2020,375000.0,"1529-1531 N CASS ST,Milwaukee,wisconsin",NaN
270,856513.0,Condominium,1682 N ASTOR ST,3.0,5955.0,Condo Duplex,2.0,1887.0,5.0,1.0,2.0,2.0,0.0,1.0,8/27/2020,210000.0,"1682 N ASTOR ST,Milwaukee,wisconsin",136.986958

In [196]:
null_sqft = null_sqft.rename(columns={'AREA':'FinishedSqft'})
null_sqft=null_sqft.reset_index(drop=True)

In [197]:
null_sqft['FinishedSqft']=null_sqft['FinishedSqft']*10.6
null_sqft

,PropertyID,PropType,Address,District,nbhd,Style,Stories,Year_Built,Rooms,Units,Bdrms,Fbath,Hbath,Lotsize,Sale_date,Sale_price,Location,latitude,longitude,FinishedSqft
0,863164.0,Residential,3102 N HACKETT AV,3.0,3060.0,Mansion,2.0,1922.0,11.0,1.0,5.0,3.0,2.0,8400.0,12/24/2020,690000.0,"3102 N HACKETT AV,Milwaukee,wisconsin",43.074923,-87.876505,3294.568733
1,855891.0,Residential,3218 N DOWNER AV,3.0,3160.0,Duplex N/S,2.0,1958.0,12.0,2.0,7.0,3.0,1.0,5160.0,8/5/2020,377600.0,"3218 N DOWNER AV,Milwaukee,wisconsin",43.076113,-87.877580,1563.831096
2,850562.0,Residential,3234 N HACKETT AV,3.0,3060.0,Residence O/S 2sty+,2.0,1906.0,10.0,1.0,6.0,3.0,0.0,6000.0,3/24/2020,449000.0,"3234 N HACKETT AV,Milwaukee,wisconsin",43.076458,-87.876441,1427.231382
3,852109.0,Residential,3235 N SHEPARD AV,3.0,3060.0,Residence O/S 2sty+,2.0,1908.0,9.0,1.0,5.0,1.0,1.0,4200.0,4/28/2020,303000.0,"3235 N SHEPARD AV,Milwaukee,wisconsin",43.076450,-87.874725,1282.101359
4,852020.0,Residential,3218 N SHEPARD AV,3.0,3060.0,Residence O/S 2sty+,2.0,1904.0,9.0,1.0,4.0,3.0,1.0,4800.0,5/7/2020,494000.0,"3218 N SHEPARD AV,Milwaukee,wisconsin",43.076120,-87.874173,1164.824081
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
266,856126.0,Residential,1027-1029 E KEWAUNEE ST,3.0,3240.0,Duplex O/S,2.0,1900.0,12.0,2.0,5.0,2.0,0.0,3450.0,3/13/2020,243000.0,"1027-1029 E KEWAUNEE ST,Milwaukee,wisconsin",43.051751,-87.899527,NaN
267,856135.0,Residential,1512-1514 N MARSHALL ST,3.0,3240.0,Duplex O/S,2.0,1890.0,11.0,2.0,4.0,2.0,0.0,3840.0,7/24/2020,280000.0,"1512-1514 N MARSHALL ST,Milwaukee,wisconsin",43.041708,-87.900573,NaN
268,850242.0,Residential,1534 N MARSHALL ST,3.0,3240.0,Duplex O/S,2.0,1886.0,12.0,2.0,6.0,2.0,0.0,3840.0,3/27/2020,232500.0,"1534 N MARSHALL ST,Milwaukee,wisconsin",43.050163,-87.900608,1638.088959
269,851581.0,Residential,1529-1531 N CASS ST,3.0,3240.0,Duplex O/S,2.0,1893.0,14.0,2.0,5.0,3.0,0.0,3840.0,4/23/2020,375000.0,"1529-1531 N CASS ST,Milwaukee,wisconsin",43.046942,-87.902241,NaN
270,856513.0,Condominium,1682 N ASTOR ST,3.0,5955.0,Condo Duplex,2.0,1887.0,5.0,1.0,2.0,2.0,0.0,1.0,8/27/2020,210000.0,"1682 N ASTOR ST,Milwaukee,wisconsin",43.052498,-87.899305,1452.061757

In [198]:
combined_sqft_not_null = combined_sqft_not_null.reset_index(drop=True)
combined_sqft_not_null

,PropertyID,PropType,Address,District,nbhd,Style,Stories,Year_Built,Rooms,FinishedSqft,Units,Bdrms,Fbath,Hbath,Lotsize,Sale_date,Sale_price,Location,latitude,longitude
0,151330.0,Residential,3118 N MARIETTA AV,3.0,3060.0,Residence O/S,2.0,1908.0,9.0,2839.0,1.0,5.0,2.0,1.0,4800.0,11/1/2019,572000.0,"3118 N MARIETTA AV,Milwaukee,wisconsin",43.075143,-87.873036
1,151369.0,Residential,3233 N HACKETT AV,3.0,3060.0,Residence O/S,2.0,1908.0,12.0,3632.0,1.0,6.0,3.0,1.0,5400.0,6/28/2019,395000.0,"3233 N HACKETT AV,Milwaukee,wisconsin",43.076378,-87.877039
2,151385.0,Residential,2708 E HAMPSHIRE ST,3.0,3060.0,Residence O/S,2.0,1903.0,9.0,3249.0,1.0,5.0,3.0,1.0,8400.0,9/27/2019,531000.0,"2708 E HAMPSHIRE ST,Milwaukee,wisconsin",43.075856,-87.876427
3,151438.0,Residential,3263-3265 N HACKETT AV,3.0,3060.0,Townhouse,2.0,1901.0,15.0,3276.0,2.0,9.0,3.0,NaN,4800.0,5/3/2019,280000.0,"3263-3265 N HACKETT AV,Milwaukee,wisconsin",NaN,NaN
4,151451.0,Residential,2717-2719 E HARTFORD AV,3.0,3060.0,Duplex O/S,2.0,1905.0,12.0,3518.0,2.0,5.0,3.0,1.0,2800.0,9/20/2019,325000.0,"2717-2719 E HARTFORD AV,Milwaukee,wisconsin",43.077659,-87.890873
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1255,192765.0,Condominium,"904 E PLEASANT ST, Unit 2-F",3.0,5980.0,Low Rise 1-3 Stories,2.0,1870.0,5.0,1095.0,1.0,1.0,1.0,0.0,0.0,07/06/2023,215000.0,"904 E PLEASANT ST, Unit 2-F,Milwaukee,wisconsin",NaN,NaN
1256,192769.0,Condominium,"912 E PLEASANT ST, Unit 2",3.0,5980.0,Low Rise 1-3 Stories,1.0,1870.0,5.0,1112.0,1.0,2.0,1.0,0.0,0.0,11/07/2023,220000.0,"912 E PLEASANT ST, Unit 2,Milwaukee,wisconsin",NaN,NaN
1257,192774.0,Condominium,"920 E PLEASANT ST, Unit 1",3.0,5980.0,Low Rise 1-3 Stories,1.0,1870.0,5.0,1513.0,1.0,3.0,1.0,0.0,0.0,06/12/2023,340000.0,"920 E PLEASANT ST, Unit 1,Milwaukee,wisconsin",NaN,NaN
1258,192930.0,Condominium,"1658 N JACKSON ST, Unit 101",3.0,5661.0,Condo Townhouse,2.0,2005.0,5.0,2395.0,1.0,3.0,2.0,1.0,1.0,11/29/2023,707000.0,"1658 N JACKSON ST, Unit 101,Milwaukee,wisconsin",NaN,NaN
1259,193071.0,Condominium,"1653 N JACKSON ST, Unit 101",3.0,5752.0,Low Rise 1-3 Stories,1.0,2007.0,3.0,1030.0,1.0,1.0,1.0,0.0,0.0,12/15/2023,300000.0,"1653 N JACKSON ST, Unit 101,Milwaukee,wisconsin",NaN,NaN

In [199]:
full_data = pd.concat([combined_sqft_not_null,null_sqft], axis=0)

In [200]:
full_data = full_data.reset_index(drop=True)

In [201]:
full_data

,PropertyID,PropType,Address,District,nbhd,Style,Stories,Year_Built,Rooms,FinishedSqft,Units,Bdrms,Fbath,Hbath,Lotsize,Sale_date,Sale_price,Location,latitude,longitude
0,151330.0,Residential,3118 N MARIETTA AV,3.0,3060.0,Residence O/S,2.0,1908.0,9.0,2839.000000,1.0,5.0,2.0,1.0,4800.0,11/1/2019,572000.0,"3118 N MARIETTA AV,Milwaukee,wisconsin",43.075143,-87.873036
1,151369.0,Residential,3233 N HACKETT AV,3.0,3060.0,Residence O/S,2.0,1908.0,12.0,3632.000000,1.0,6.0,3.0,1.0,5400.0,6/28/2019,395000.0,"3233 N HACKETT AV,Milwaukee,wisconsin",43.076378,-87.877039
2,151385.0,Residential,2708 E HAMPSHIRE ST,3.0,3060.0,Residence O/S,2.0,1903.0,9.0,3249.000000,1.0,5.0,3.0,1.0,8400.0,9/27/2019,531000.0,"2708 E HAMPSHIRE ST,Milwaukee,wisconsin",43.075856,-87.876427
3,151438.0,Residential,3263-3265 N HACKETT AV,3.0,3060.0,Townhouse,2.0,1901.0,15.0,3276.000000,2.0,9.0,3.0,NaN,4800.0,5/3/2019,280000.0,"3263-3265 N HACKETT AV,Milwaukee,wisconsin",NaN,NaN
4,151451.0,Residential,2717-2719 E HARTFORD AV,3.0,3060.0,Duplex O/S,2.0,1905.0,12.0,3518.000000,2.0,5.0,3.0,1.0,2800.0,9/20/2019,325000.0,"2717-2719 E HARTFORD AV,Milwaukee,wisconsin",43.077659,-87.890873
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1526,856126.0,Residential,1027-1029 E KEWAUNEE ST,3.0,3240.0,Duplex O/S,2.0,1900.0,12.0,NaN,2.0,5.0,2.0,0.0,3450.0,3/13/2020,243000.0,"1027-1029 E KEWAUNEE ST,Milwaukee,wisconsin",43.051751,-87.899527
1527,856135.0,Residential,1512-1514 N MARSHALL ST,3.0,3240.0,Duplex O/S,2.0,1890.0,11.0,NaN,2.0,4.0,2.0,0.0,3840.0,7/24/2020,280000.0,"1512-1514 N MARSHALL ST,Milwaukee,wisconsin",43.041708,-87.900573
1528,850242.0,Residential,1534 N MARSHALL ST,3.0,3240.0,Duplex O/S,2.0,1886.0,12.0,1638.088959,2.0,6.0,2.0,0.0,3840.0,3/27/2020,232500.0,"1534 N MARSHALL ST,Milwaukee,wisconsin",43.050163,-87.900608
1529,851581.0,Residential,1529-1531 N CASS ST,3.0,3240.0,Duplex O/S,2.0,1893.0,14.0,NaN,2.0,5.0,3.0,0.0,3840.0,4/23/2020,375000.0,"1529-1531 N CASS ST,Milwaukee,wisconsin",43.046942,-87.902241
1530,856513.0,Condominium,1682 N ASTOR ST,3.0,5955.0,Condo Duplex,2.0,1887.0,5.0,1452.061757,1.0,2.0,2.0,0.0,1.0,8/27/2020,210000.0,"1682 N ASTOR ST,Milwaukee,wisconsin",43.052498,-87.899305

In [202]:
full_data=full_data.drop(['Address'],axis=1)

In [203]:
full_data.isnull().sum()

PropertyID        0
PropType          0
District          0
nbhd              0
Style             0
Stories           2
Year_Built        0
Rooms             0
FinishedSqft     73
Units             0
Bdrms             0
Fbath             0
Hbath           294
Lotsize           0
Sale_date         0
Sale_price        0
Location          0
latitude        587
longitude       587
dtype: int64

In [204]:
full_data = full_data.dropna(subset=["Stories","FinishedSqft"], axis=0)

In [205]:
full_data['Hbath'] = full_data['Hbath'].fillna(0)

Considering Half Bath Null Values as not Zero because, the house has no half bathroom

In [206]:
null_values(full_data)

PropertyID        0
PropType          0
District          0
nbhd              0
Style             0
Stories           0
Year_Built        0
Rooms             0
FinishedSqft      0
Units             0
Bdrms             0
Fbath             0
Hbath             0
Lotsize           0
Sale_date         0
Sale_price        0
Location          0
latitude        585
longitude       585
dtype: int64

In [209]:
full_data.shape

(1456, 19)

In [215]:
full_data = full_data.assign(City='Milwaukee', State='Wisconsin', Country='United States of America')

In [237]:
full_data.to_csv('Data1/previous_sale_data.csv',index=False)

In [233]:
full_data=pd.read_csv('Data1/previous_sale_data.csv')

In [234]:
full_data.isna().sum()

PropertyID        0
PropType          0
District          0
nbhd              0
Style             0
Stories           0
Year_Built        0
Rooms             0
FinishedSqft      0
Units             0
Bdrms             0
Fbath             0
Hbath             0
Lotsize           0
Sale_date         0
Sale_price        0
Location          0
latitude        585
longitude       585
City              0
State             0
Country           0
dtype: int64

In [235]:
full_data = full_data[full_data['latitude'].notna()]

In [236]:
full_data.isna().sum()

PropertyID      0
PropType        0
District        0
nbhd            0
Style           0
Stories         0
Year_Built      0
Rooms           0
FinishedSqft    0
Units           0
Bdrms           0
Fbath           0
Hbath           0
Lotsize         0
Sale_date       0
Sale_price      0
Location        0
latitude        0
longitude       0
City            0
State           0
Country         0
dtype: int64